version: "3"
services:
  jenkins:
    container_name: jenkins
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - net_jenkins_sonarqube
    
  # sonarqube:
  #   container_name: sonarqube
  #   image: sonarqube:8.7.1-community
  #   ports:
  #     - "9000:9000"
  #     - "9092:9092"
  #   volumes:
  #     - sonarqube_home:/var/sonarqube_home
  #   networks:
  #     - net_jenkins_sonarqube
    
volumes:
  jenkins_home:
  # sonarqube_home:

networks:
  net_jenkins_sonarqube: