version: "3"
services:
  jenkins:
    container_name: jenkins_compose
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    
volumes:
  jenkins_home: